version: '3'

services:
  auth:
    restart: always
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    environment:
      JWT_KEY: secret
      MONGO_URI: mongodb://auth-db:27017/auth
    ports:
      - '3001:3001'
    depends_on:
      - auth-db

  auth-db:
    image: mongo
    ports:
      - '27017:27017'

  client:
    ports:
      - 3000:3000
    build:
      context: ./services/client
      dockerfile: Dockerfile
    depends_on:
      - auth
